# Generated by Django 4.2.7 on 2023-12-05 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitioTurnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='servicio',
        ),
        migrations.AddField(
            model_name='servicio',
            name='profesional_a_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitioTurnos.profesional'),
        ),
    ]
