# Generated by Django 4.2.7 on 2023-12-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitioTurnos', '0002_remove_profesional_servicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
