# Generated by Django 4.2.7 on 2023-11-28 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitioTurnos', '0002_alter_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sitioTurnos.especialidad'),
        ),
    ]
